resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 60
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 50
      permittedNumberOfCallsInHalfOpenState: 15
      automaticTransitionFromOpenToHalfOpenEnabled: false
      waitDurationInOpenState: 60s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 1000ms
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
  instances:
    inventory:
      baseConfig: default
    price:
      baseConfig: default
    reviews:
      baseConfig: default

resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 100
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions:
        - java.util.concurrent.TimeoutException
        - io.github.resilience4j.circuitbreaker.CallNotPermittedException
  instances:
    inventory:
      baseConfig: default
    price:
      baseConfig: default
    reviews:
      baseConfig: default

resilience4j.timelimiter:
  configs:
    default:
      cancelRunningFuture: true
      timeoutDuration: 2s
  instances:
    inventory:
      baseConfig: default
    price:
      baseConfig: default
    reviews:
      baseConfig: default